import PDFDocument from "pdfkit"

export const generatePDF = async (data) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            size: "A4",
            margin: 50,
            info: {
                Author: "MultivexAI",
                Title: data?.title || "Generated Document",
                Creator: "MultivexAI",
            },
        })

        const chunks = []
        doc.on("data", (chunk) => chunks.push(chunk))
        doc.on("end", () => resolve(Buffer.concat(chunks)))
        doc.on("error", (err) => reject(err))

        doc
            .font("Helvetica")
            .fontSize(24)
            .text(data?.title || "Generated Document", {
                align: "center"
            })
            .fillColor("#111827")

        //subtitle
        if (data?.subtitle) {
            doc.moveDown(0.5)
            doc
                .font("Helvetica")
                .fontSize(15)
                .text(data.subtitle, {
                    align: "center",
                })
                .fillColor("#6B7280")
        }

        doc.moveDown(2)

        //sections
        data?.sections?.forEach((section) => {
            doc
                .font("Helvetica-Bold")
                .fontSize(18)
                .text(section.heading, {
                    align: "left",
                })
                .fillColor("#111827")

            doc.moveDown(0.5)

            //section points
            section.points?.forEach((point) => {
                doc
                    .font("Helvetica")
                    .fontSize(14)
                    .text("• " + point, {
                        lineGap: 4,
                        align: "left",
                        indent: 20,
                    })
                    .fillColor("#111827")
            })
            doc.moveDown(1)
        });

        //footer
        doc.moveDown(2)
        doc
            .font("Helvetica")
            .fontSize(10)
            .text("Generated by MultivexAI", {
                align: "center",
            })
            .fillColor("#6B7280")

        doc.end()
    })
}