import pptxgen from "pptxgenjs";

const COLORS = {
    primary: "003366",
    secondary: "FFFFFF",
    accent: "FF6600",
    text: "334155",
    light: "F3F4F6",
    border: "E5E7EB",
    white: "FFFFFF",
    muted: "9CA3AF",
};

export const generatePPT = async (data) => {
    const pptx = new pptxgen()
    pptx.layout = "LAYOUT_WIDE"
    pptx.author = "MultivexAI"
    pptx.title = data?.title || "Generated Presentation"
    pptx.subject = data?.subtitle || ""
    pptx.company = "MultivexAI"
    pptx.theme = {
        headFontFace: "Aptos",
        bodyFontFace: "Aptos",
        lang: "en-US",
    }

    addCoverSlide(pptx, data)

    const slides = Array.isArray(data?.slides) ? data.slides : []
    slides.forEach((slide, i) => {
        addContentSlide(pptx, slide?.title, slide?.points || [], i + 1, slides.length)
    })

    addThankYouSlide(pptx)

    // pptxgenjs write() returns a Buffer in Node
    return pptx.write({ outputType: "nodebuffer" })
}

const addCoverSlide = (pptx, data) => {
    const slide = pptx.addSlide()
    slide.background = { color: COLORS.primary }

    slide.addShape(pptx.ShapeType.rect, {
    x: 0,
    y: 0,
    w: "13.33",
    h: "0.18",
    fill: { color: "60A5FA" },
    line: { color: "60A5FA" },
})

slide.addText(data?.title || "Generated Presentation", {
    x: 0.7,
    y: 1.7,
    w: 12,
    h: 0.8,
    align: "center",
    color: COLORS.white,
    bold: true,
    fontSize: 28,
})

slide.addText(data?.subtitle || "", {
    x: 0.7,
    y: 2.5,
    w: 12,
    h: 0.8,
    align: "center",
    color: "DBEAFE",
    fontSize: 15,
})

slide.addText("Generated by MultivexAI", {
    x: 0,
    y: 6.5,
    w: 13.33,
    h: 0.2,
    align: "center",
    color: "BFDBFE",
    fontSize: 10,
})
}

const addContentSlide = (pptx, title, points, slideNumber, totalSlides) => {
    const slide = pptx.addSlide()
    slide.background = { color: COLORS.white }

slide.addText(title || `Slide ${slideNumber}`, {
    x: 0.5,
    y: 0.35,
    w: 10,
    h: 0.8,
    color: COLORS.text,
    bold: true,
    fontSize: 20,
})

slide.addShape(pptx.ShapeType.line, {
    x: 0.5,
    y: 0.85,
    w: 12,
    h: 0,
    line: { color: COLORS.border, width: 1.2 },
})

const visualPoints = points.slice(0, 6)
visualPoints.forEach((point, index) => {
    const y = 1.2 + index * 0.75

    slide.addShape(pptx.ShapeType.roundRect, {
        x: 0.5,
        y: y,
        w: 12,
        h: 0.58,
        fill: { color: index % 2 ? "F8FAFC" : "EFF6FF" },
        line: { color: COLORS.border, width: 1 },
        radius: 0.08,
    })

    slide.addShape(pptx.ShapeType.ellipse, {
        x: 0.92,
        y: y + 0.15,
        w: 0.12,
        h: 0.12,
        fill: { color: COLORS.primary },
        line: { color: COLORS.primary },
    })

    slide.addText(point, {
        x: 1.2,
        y: y + 0.08,
        w: 10,
        h: 0.35,
        color: COLORS.text,
        fontSize: 15,
        fit: "shrink",
    })
})

    slide.addText(`Slide ${slideNumber}/${totalSlides}`, {
        x: 12.1,
        y: 5.8,
        w: 0.8,
        h: 0.2,
        align: "right",
        color: COLORS.muted,
        fontSize: 10,
    })

    slide.addText("MultivexAI", {
        x: 0.5,
        y: 5.8,
        w: 2,
        h: 0.2,
        align: "left",
        color: COLORS.muted,
        fontSize: 10,
    })
}

const addThankYouSlide = (pptx) => {
    const slide = pptx.addSlide()
    slide.background = { color: COLORS.secondary }

    slide.addText(`Thank You`, {
        x: 0,
        y: 2.2,
        w: 13.33,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        fontSize: 34,
        bold: true,
    })

    slide.addText(`Generated by MultivexAI`, {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "94A3B8",
        fontSize: 10,
    })
}
